### ISSUE TITLE
mp3cast~ does not allow to inject tags during stream

### ISSUE THREAD

**Issue by Jackovic** [pd-externals/mp3cast#2]
mp3cast~ does not allow to inject tags during the stream to change title and/or artist name.

**Comment by reduzent** [comment]
There is a new method `icy-title` that accepts a symbol and updates the song information of an Icecast2 stream.

**Comment by Jackovic** [comment]
Hello !
I get the message in Icecast2, so it is working !
But, I get an audio click each time I send the message 'icy-title'.

**Comment by reduzent** [comment]
I see. I didn't notice that because the server I test with is quite close and my internet connection is good. 

Updating the icy-title requires a second connection, more precisely: a HTTP GET request, because - as I was told on #icecast - MP3 and AAC do not allow for interleaving metadata into the streams. The request is blocking, so when establishing the connection and sending the request takes more time than the length of Pd's audio buffer, you get a drop-out in Pd's audio output. However, the audio in the stream shouldn't be affected by that, since Icecast seems to buffer 4 seconds worth of audio. I can do non-realtime-safe stuff in Pd without noticing it in the stream. 

Making [mp3cast~] truly realtime-safe requires a lot more work, from what I can tell. I won't dig into this for now, because I'm not sure I'm experienced enough to properly program it and also I think it is easy enough to de-couple Pd from the streaming by other means.  

For instance:
```
ffmpeg -f jack -i jack-client-name -codec:a libmp3lame -qscale:a 2 -content_type 'audio/mpeg' -vn -f mp3 icecast://source:hackme@example.org:8000/live.mp3
```

Having said that, the `icy-title` method could be improved a bit by not performing a hostname lookup again.

**Comment by reduzent** [comment]
e82e3296a59b41592c1430a0e2b70d7e119f108d avoids the second hostname lookup when updating the song title. I'm curious: Does that already improve the situation?

**Comment by reduzent** [comment]
I close this since the blocking nature of [mp3cast~] is a different issue.

**Comment by Jackovic** [comment]
Yes, using jack (or pulseaudio|alsa loopback) with ffmpeg or gstreamer can help. Thanks.
I understand that there is a lot of work to be done to get rid of the dropout.
Also, without the second hostname loopkup, i didn't notice change.

I know it is not related to mp3cast~ or this issue, but is it a big deal to make Pd externals based on ffmpeg ?
